pipeline {

agent any

stages {

stage('Maven build') {
    steps {    
      bat 'mvn -f braccotest1/pom.xml clean install'
    }

}

stage('Deploy CloudHub') {

environment {

ANYPOINT_CREDENTIALS = credentials('anypoint.credentials')

}



steps {

echo 'Deploying mule project due to the latest code commit…'

echo 'Deploying to the configured environment….'

bat 'mvn -f braccotest1/pom.xml package deploy -Dmule.artifact=target/braccotest1-1.0.0-SNAPSHOT-mule-app.jar -Dusername=$ANYPOINT_CREDENTIALS_USR -Dpassword=$ANYPOINT_CREDENTIALS_PSW -Denvironment=Sandbox -DmuleDeploy'
}

}

}

}